version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
    - pip install poetry
    - poetry config virtualenvs.create false
    - |
      curl -L micro.mamba.pm/install.sh -o install.sh
      bash install.sh --shell=bash
    - micromamba install -c conda-forge openmm swig pdbfixer

sphinx:
  configuration: docs/conf.py
  
python:
  install:
    - requirements: docs/doc_requirements.txt
