version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
    - pip install poetry
    - pip install torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cpu
    - pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.1+cpu.html
    - poetry config virtualenvs.create false
    - poetry install

sphinx:
  configuration: docs/conf.py
  
python:
  install:
    - requirements: docs/doc_requirements.txt
